builds:
  - binary: teler
    main: main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/kitabisa/teler/common.Version=v{{.Version}}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^chore"
      - "^style"
      - "^refactor"
      - "^test"
      - Merge pull request
      - Merge branch
      - go mod tidy