name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Code
        uses: actions/checkout@master

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}